#!/bin/sh
# Compiles userfunctions.c against the libpq of every PostgreSQL release this
# library supports, and reports how many functions each one binds.
#
# Only the two headers are needed to answer the question this asks -- does
# the source still compile, and does it bind what it should -- so that is all
# this fetches, from the release tag of each version. No library is linked
# and nothing is run.
#
# The list is the first and the latest minor of every supported major,
# because what is bound is decided per major: libpq has not added or removed
# a function in a minor release in any of the ten majors from 9.6 to 18, and
# PostgreSQL's policy is that minor releases carry fixes rather than
# features. The .0 of each major is therefore the floor the version gates in
# userfunctions.c actually promise, and it is checked rather than assumed.
#
# Usage:
#   scripts/check-versions.sh              every supported version
#   scripts/check-versions.sh 17.11 18.6   only these
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root" || exit 1

# The versions the makefile pins digests for, and what each should bind.
# A number that moves is either a real change or a mistake, and either way
# it is worth seeing rather than discovering later.
default_versions='14.0 14.24 15.0 15.19 16.0 16.15 17.0 17.11 18.0 18.6 19beta3'
expected_14=113
expected_15=113
expected_16=114
expected_17=132
expected_18=133
expected_19=133

versions=${*:-$default_versions}
cache=${CLIPSPG_HEADER_CACHE:-vendor/headers}
# The CLIPS headers to compile against. The makefile points this at the
# pristine tree for whichever CLIPS_VERSION is selected; vendor/clips, the
# symlink to the version built last, is the fallback for a run by hand.
clips=${CLIPS_INCLUDE:-vendor/clips}
CC=${CC:-cc}

[ -f "$clips/clips.h" ] || {
    echo "check-versions: no CLIPS headers in $clips -- run 'make clips-source'" >&2
    echo "  first, or point at a tree with CLIPS_INCLUDE=/path/to/clips" >&2
    exit 1
}

fetch() {
    if command -v curl >/dev/null 2>&1; then curl -fsS -o "$2" "$1"
    elif command -v wget >/dev/null 2>&1; then wget -q -O "$2" "$1"
    else echo "check-versions: neither curl nor wget is installed" >&2; exit 1
    fi
}

# 18.6 -> REL_18_6, 19beta3 -> REL_19_BETA3
tag_for() {
    printf 'REL_%s\n' "$1" | sed -e 's/\./_/g' -e 's/beta/_BETA/' -e 's/rc/_RC/'
}

status=0

for version in $versions; do
    major=${version%%.*}
    major=${major%%beta*}
    major=${major%%rc*}
    tag=$(tag_for "$version")
    dir=$cache/$tag
    raw=https://raw.githubusercontent.com/postgres/postgres/$tag

    if [ ! -f "$dir/libpq-fe.h" ]; then
        mkdir -p "$dir"
        fetch "$raw/src/interfaces/libpq/libpq-fe.h" "$dir/libpq-fe.h"
        fetch "$raw/src/include/postgres_ext.h" "$dir/postgres_ext.h"
        # PostgreSQL 17 and earlier include this from postgres_ext.h, and it
        # is generated by configure rather than shipped. Only one line of it
        # matters to a compile of this file.
        grep -q 'pg_config_ext' "$dir/postgres_ext.h" &&
            printf '#define PG_INT64_TYPE long int\n' > "$dir/pg_config_ext.h"
    fi

    # The number the makefile would pass for this version.
    minor=$(printf '%s\n' "$version" | sed -n 's/^[0-9]*\.\([0-9]*\)$/\1/p')
    num=$(printf '%d%04d' "$major" "${minor:-0}")

    printf '%-9s ' "$version"

    if ! $CC -fsyntax-only -Wall -Werror -I "$clips" -I "$dir" -DLINUX \
             -DCLIPSPG_PG_VERSION_NUM="$num" userfunctions.c 2>"$dir/errors"; then
        echo "FAILED to compile"
        sed 's/^/    /' "$dir/errors" | head -10
        status=1
        continue
    fi

    bound=$($CC -E -I "$clips" -I "$dir" -DLINUX -DCLIPSPG_PG_VERSION_NUM="$num" \
                userfunctions.c 2>/dev/null | grep -c 'AddUDF(env,"pq-')

    eval "want=\${expected_$major:-}"
    if [ -n "$want" ] && [ "$bound" -ne "$want" ]; then
        echo "compiles, binds $bound functions -- expected $want"
        status=1
    else
        echo "compiles, binds $bound functions"
    fi
done

exit $status
